import React from 'react';
import ProductPage from "../../../productPage/ProductPage";
import ProductMobile from "../../../productPage/mobile/ProductMobile"
import {HeaderFooterProvider} from "../../../Components";
import {useRouter} from "next/router";
import Head from "next/head";

const ProductPageInformation = () => {
    const router = useRouter()
    return (
        // <HeaderFooterProvider>
        <>

            <Head>
                <title>فروشگاه اینترنتی اکالا | {router.query.productName.replace(/-/g, " ")}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ProductMobile productId={router.query.productId}/>
            <ProductPage productId={router.query.productId}/>
        {/*</HeaderFooterProvider>*/}
            </>
    );
};

export default ProductPageInformation;

export async function getStaticPaths() {

    return {
        paths: [
            {params: {productId: '1' , productName: 'صفحه محصول'}}
        ],
        fallback: 'blocking'
    };
}

export async function getStaticProps(context) {
    console.log(context)
    let ProductList = []

    return {
        props: {ProductList}, // will be passed to the page component as props
    }
}